// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkknnhlnmizmwisqlfic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indra25uaGxubWl6bXdpc3FsZmljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjU1NzUsImV4cCI6MjA3MDkwMTU3NX0._XkX05u9oAlBG3s3ucx9neWwvL29hbHfqk7IP2BW6Xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});